### ISSUE TITLE
Does not work on Chrome latest

### ISSUE THREAD

**Issue by spiess-demos** [mathislucka/a11y-datepicker#1]
When testing the Demo in Google Chrome Version 83.0.4103.106 (Offizieller Build) (64-Bit) for Windows 10, the Datepicker window is only opening for a short flickering amount of time and then dissappears again, only to never appear again.

**Comment by spiess-demos** [comment]
Apparently this is a side effect of the chrome extension "[Ghostery](https://chrome.google.com/webstore/detail/ghostery-%E2%80%93-privacy-ad-blo/mlomiejdfkolichcflejclcbmpeaniij)".

**Comment by mathislucka** [comment]
Thanks for the heads up.
a11y-datepicker sets a class on each element within the datepicker. The class consists of a prefix and the element's tagName (e.g. `ad-table`). The default value for the prefix was `ad` which Ghostery apparently mistook for an advertisement related element. Hence it blocked js execution.

I fixed it with bc23de257c73c5debde918bd0f48c9ae99e4cc99
